### ISSUE TITLE
Remove Nokogiri dependency

### ISSUE THREAD

**Issue by syntaxTerr0r** [michaelbaudino/addic7ed-ruby#28]
Hello there,

Nokogiri requires to build a native C extension (and the presence of libxml2-dev & libxslt1-dev).
It can become a real pain to have it installed & working on some NAS / Mediacenter systems.

Is Nokogiri really required here?

**Comment by syntaxTerr0r** [comment]
https://github.com/YorickPeterse/oga might be interesting in replacement.

**Comment by michaelbaudino** [comment]
This issue has been fixed a long time ago, so I'm closing it, thanks again @syntaxTerr0r ❤️
