### ISSUE TITLE
Getting hearing impaired versions of subtitles

### ISSUE THREAD

**Issue by nem0rder** [michaelbaudino/addic7ed-ruby#9]
Hej 

I am getting the hearing impaired version of the subtitles when i use the script. Any work a round?

**Comment by michaelbaudino** [comment]
Hi @nem0rder,

Sorry I totally missed your issue in my notifications :confused: 
Unfortunately, no, there is no such feature yet, but I know @Pmaene has been working on such a thing [recently](https://github.com/Pmaene/addic7ed-ruby/commit/8ae4e08bb853f9bd0654d8e68a9aed54df06091b).
Feel free to try [his fork](https://github.com/Pmaene/addic7ed-ruby) or to convince him to submit a PR :wink:
